### ISSUE TITLE
feature request: please support vue-class-component

### ISSUE THREAD

**Issue by AnWeber** [ktsn/vue-router-layout#23]
Please add .d.ts which extends vue-class-componet ComponentOptions to support writing code like this example.

```
@Component({
  layout: "testlayout",
})
export default class Test extends Vue {
```

**Comment by ktsn** [comment]
Well, it already has type declaration file. I suspect your typescript config might be wrong somehow.
If you are sure this is vue-router-layout issue. Please provide a reproduction (example GitHub repo etc.).

**Comment by AnWeber** [comment]
you are right. I overlooked the index.d.ts. 

Thanks
