### ISSUE TITLE
Bug report] The created hook in page is wrongly called when layout changes in Vue3.

### ISSUE THREAD

**Issue by Azurewarth0920** [ktsn/vue-router-layout#333]
Reproduction repo: https://github.com/Azurewarth0920/created-called-before-routechange

It seems like when changing the layout in the [beforeRouteUpdate hook](https://github.com/ktsn/vue-router-layout/blob/master/src/index.ts#L162) will cause the sub-route component to rerender.

**Comment by wulucxy** [comment]
@Azurewarth0920 same problem here，do you solve this?

**Comment by Azurewarth0920** [comment]
@wulucxy 
Fixed here.
I'll mention the author to take a look at this pull request: https://github.com/ktsn/vue-router-layout/pull/334
